Добавляет маршрутизацию
htmlacademy-react/116316-six-cities-9 pull request #4
Opened 2022-02-23 20:32 UTC by Sharky121

2022-02-24 10:03 UTC, ekazakov requested changes

2022-02-24 10:03 UTC, ekazakov commented on project/src/components/app/app.tsx
> +        <Route path={AppRoute.Favorites} element={
В место Route тут надо сразу вызывать PrivateRoute. И в приватный роут передавать path
Вот как можно сделать приватный роут https://github.com/ekazakov/976593-six-cities-5/blob/master/src/components/private-route/private-route.jsx

А на лекции как объясняли про приватные роуты? Просто раньше сразу показывали пример кода, а как сейчас?

2022-02-26 21:19 UTC, Sharky121 commented on project/src/components/main-screen/main-screen.tsx
> +              <Logo/>
Вынес в header в отдельный компонент. Пока единственное не понял, как в нём отображать разные состояния - пользователь залогирован или нет. Или например на странице входа вообще нет блока со статусом юзера.

2022-02-26 21:38 UTC, Sharky121 commented on project/src/components/app/app.tsx
> +        <Route path={AppRoute.Favorites} element={
Эту часть я сделал также как на лекции. Код один в один. Я потом полез погуглить эту тему, нашел статью https://dev.to/iamandrewluca/private-route-in-react-router-v6-lg5 . Если я правильно понял, то так описывается приватный маршрут в 6-й версии.

2022-02-27 22:18 UTC, ekazakov commented on project/src/components/main-screen/main-screen.tsx
> +              <Logo/>
В компонент Header можно передавать дополнительные пропсы, тип isUserAuthorized или hideUserBlock.

В коде это будет как-то так:

```jsx
const Header = ({isUserAuthorized}) => { 

   return <div>
      <div>Menu Item...</div>
      {isUserAuthorized ? <UserStatus/> : null}
   </div>
}
```

2022-02-27 22:19 UTC, ekazakov commented on project/src/components/app/app.tsx
> +        <Route path={AppRoute.Favorites} element={
Да, не заметил что в 6 роутере поменяли это. Тогда все ок

2022-02-27 22:19 UTC, merged