Обратная сторона реальности
htmlacademy-react/116316-six-cities-9 pull request #5
Opened 2022-03-14 20:21 UTC by Sharky121

2022-03-14 23:20 UTC, ekazakov requested changes

2022-03-14 23:20 UTC, ekazakov commented on project/src/components/app/app.tsx
> +          element={<MainScreen placesCount = {placesCount} offers = {offers}/>}
placesCount лучше считать из кол-во офферов

2022-03-14 23:20 UTC, ekazakov commented on project/src/components/reviews-form/reviews-form.tsx
> +      </div>
Это можно вынести в отдельный компонент и каждую радиокнопку тоже

2022-03-14 23:20 UTC, ekazakov commented on project/src/components/main-screen/main-screen.tsx
> +              <b className="places__found">{placesCount} places to stay in Amsterdam {activeOffer && activeOffer.id}</b>
Не понятно зачем тут `activeOffer && activeOffer.id`? Тут надо будет показывать выбранный город, но это потом сделаем

2022-03-15 22:23 UTC, Sharky121 commented on project/src/components/app/app.tsx
> +          element={<MainScreen placesCount = {placesCount} offers = {offers}/>}
Исправил

2022-03-15 22:24 UTC, Sharky121 commented on project/src/components/reviews-form/reviews-form.tsx
> +      </div>
Вынес в отдельный компонент радиокнопки

2022-03-15 22:25 UTC, Sharky121 commented on project/src/components/main-screen/main-screen.tsx
> +              <b className="places__found">{placesCount} places to stay in Amsterdam {activeOffer && activeOffer.id}</b>
Это я просто для теста вынес. Чтобы линтер не ругался на неиспользуемые переменные.

2022-03-16 10:01 UTC, merged