Контроль и ограничения (часть 1)
htmlacademy-react/116316-six-cities-9 pull request #7
Opened 2022-03-28 15:13 UTC by Sharky121

Привет. Вроде бы всё сделал по заданию, но затык в карте. Не пойму, почему у меня не перерисовывается карта.
Добавляются новые метки на карте при выборе нового города, а старые не удаляются. 
Я передаю в компонент Map новый сity с новым центром координат и обновленный список offers. По логике должна перерисовываться карта с центром в этом городе, ведь я указал в зависимости useEffect [city, offers]

---
:mortar_board: [Контроль и ограничения (часть 1)](https://up.htmlacademy.ru/react/9/user/116316/tasks/8)

2022-03-28 19:21 UTC, ekazakov requested changes

2022-03-28 19:21 UTC, ekazakov commented on project/src/components/main-screen/main-screen.tsx
> +  const currentState = useAppSelector((state) => state);
Лучше сразу сделать селекторы, которые отдельно достают офферы и город

2022-03-28 19:21 UTC, ekazakov commented on project/src/store/reducer.js
> +  offers: [],
Помести сюда сразу моковые офферы

2022-03-28 19:21 UTC, ekazakov commented on project/src/store/reducer.js
> +  city: cities[0],
Тут надо хранить только id выбранного города

2022-03-28 19:21 UTC, ekazakov commented on project/src/store/reducer.js
> +        state.offers.push(offer);
Менять список офферов не надо, надо сделать селектор, в котором ты будешь фильтровать офферы по id города

2022-03-28 19:21 UTC, ekazakov commented on project/src/components/main-screen/main-screen.tsx
> +function MainScreen({offers, cities}: MainScreenProps): JSX.Element {
Офферы лучше брать сразу из стора, ниже описал

2022-03-28 19:21 UTC, ekazakov commented on project/src/hooks/useMap.tsx
> +  }, [mapRef, map, city]);
Условие внутри эффекта сделано так, что изменение города на него не влияет. Надо добавить блок else и в нем менять карте координаты центра

2022-03-29 12:16 UTC, Sharky121 commented on project/src/store/reducer.js
> +  city: cities[0],
Тут немного не понял. У нас в структуре данных у offers есть city, но у него нет id. Я не понял как city связать с offers. Поэтому я не нашёл способа, кроме как сравнивать title, чтобы фильтровать. Ну и передавать актуальный город с центром и координатами в Map компонент, чтобы менять центр карты. Как вариант, вводить дополнительную функцию, которая по id возвращает объект city и дёргает оттуда данные.

2022-03-29 12:20 UTC, Sharky121 commented on project/src/components/main-screen/main-screen.tsx
> +  const currentState = useAppSelector((state) => state);
Немного не понял, что ты подразумеваешь по "сделать селекторы". Я понял это что, завести переменные, типа const cityOffersSelector = useAppSelector((state) => state.filteredOffers); Еще я видел где-то тему с createSelectors, но это какая-то библиотека reselect, пока не лекциях её не было, может где-то дальше, про оптимизацию.

2022-03-29 12:22 UTC, Sharky121 commented on project/src/store/reducer.js
> +        state.offers.push(offer);
Про селекторы отписал выше, я пока просто создал отельное поле в начальном state и в case немного отписал по другому. Если опять же я тебя правильно понял и ты не имел ввиду createSelector из библиотеки reselect

2022-03-29 13:32 UTC, ekazakov requested changes

2022-03-29 13:32 UTC, ekazakov commented on project/src/components/city/city.tsx
> +  const activeCitySelector = useAppSelector((state) => state.activeCity);
Лучше назвать переменную просто activeCity, activeCitySelector — это название для ф-и

2022-03-29 13:32 UTC, ekazakov commented on project/src/components/main-screen/main-screen.tsx
> +  const activeCitySelector = useAppSelector((state) => state.activeCity);
Селектор это ф-я которую ты передаешь в useAppSelector. Библиотеку reselct, пока применять не надо

2022-03-29 13:32 UTC, ekazakov commented on project/src/store/reducer.js
> +      state.filteredOffers = state.offers.filter((offer) => offer.city.name === state.activeCity.title);
Этот код надо выносить из стора в селектор. 
`
useAppSelector(state => state.offers.filter((offer) => offer.city.name === state.activeCity.title);
`

Идея в том, что если какие-то данные можно вычислить на основе других, то мы не храним их ни в сторе, ни в стейте компонента

2022-03-29 13:35 UTC, merged