Добро пожаловать, или посторонним вход воспрещён (часть 1)
htmlacademy-react/116316-six-cities-9 pull request #9
Opened 2022-04-04 00:55 UTC by Sharky121

2022-04-04 08:00 UTC, ekazakov requested changes

2022-04-05 13:04 UTC, Sharky121 commented on project/src/components/login-screen/login-screen.tsx
> +    if (loginRef.current !== null &&  passwordRef.current !== null) {
Привет. Добавил валидацию для авторизации. У меня тут пара вопросов возникла...  
1. У нас проверка авторизации вынесена в index. Получается, если не авторизован, то ошибка будет выпадать на всех страницах?
2. Не понимаю, откуда-то странное поведение. При входе, у меня должен хэдер перерисовываться и отображать мэйл юзера и кнопку выхода. Но так не происходит, user = null в стейте и обновляется только после обновления страниц. Не подскажешь, почему такая ошибка?

2022-04-05 17:36 UTC, ekazakov requested changes

2022-04-05 17:36 UTC, ekazakov commented on project/src/store/api-action.ts
> +      store.dispatch(requireAuthorization(AuthorizationStatus.Auth));
тут тоже надо делать store.dispatch(setUser(data)); — тогда при авторизации юзер стразу будет в сторе

2022-04-05 17:36 UTC, ekazakov commented on project/src/index.tsx
> +      <ToastContainer />
Да, тост с ошибкой будет показываться на всех страницах, т.к. ты рендеришь его в компоненте, который содержит все приложение

2022-04-05 17:36 UTC, ekazakov commented on project/src/index.tsx
> +store.dispatch(checkAuthAction());
Вообще для checkAuthAction не надо показывать ошибку, если пользователь неавторизован.
Можно в checkAuthAction сделать другой обработчик ошибки

2022-04-05 18:39 UTC, merged